### ISSUE TITLE
frozen busybox

### ISSUE THREAD

**Issue by YnsDev1** [MakiseKurisu/NVG589#1]
hi i follow your insstructions to update busybox and everything work fine , but when i reboot the ipcam , it return to initial version

can you help me please ???

**Comment by MakiseKurisu** [comment]
NVG589 is a router, not an IP camera. Assuming we are talking about the router here, NVG589 itself will perform the self update after the exploit. I didn't figure out how to disable auto update before I ironically bricked my own test router (I was trying to rebuild the kernel and the new kernel won't boot). I have since dropped this project as I'm on a different router now.
